export const ALL_CATEGORY_REQUEST = "ALL_CATEGORY_REQUEST"
export const ALL_CATEGORY_SUCCESS = "ALL_CATEGORY_SUCCESS"
export const ALL_CATEGORY_FAIL = "ALL_CATEGORY_FAIL"
export const CLEAR_ERRORS = "CLEAR_ERRORS";